openapi: 3.1.0
info:
  title: Goals APIs
  description: API for accessing my periodic hierarchical goals. For planning my typical day, prefer a combination of my daily and weekly goals.
  version: 1.0.0
servers:
  - url: https://tutor.mleclub.com
    description: personal server
paths:
  /api/goals:
    get:
      operationId: goals
      summary: Retrieve periodic goals
      description: Fetch goals for specified periods in plain text.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                periods:
                  type: array
                  items:
                    type: string
                    enum:
                      - day
                      - week
                      - month
                      - quarter
                      - year
              required:
                - periods
      responses:
        "200":
          description: A JSON object containing the goals for the specified periods.
          content:
            application/json:
              schema:
                type: object
                properties:
                  results:
                    type: object
                    description: Mapping of file paths to goal contents.
                    additionalProperties:
                      type: string
                      description: Content of the goals file for the period.
        "400":
          description: Bad Request. Invalid period specified.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
